name: fltr_alquran_if
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  adhan: ^2.0.0+1
  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_qiblah: ^2.2.0
  flutter_shimmer: ^2.1.2
  geocoding: ^2.1.1
  geolocator: ^9.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.1.0
  intl: ^0.18.1
  just_audio: ^0.9.35
  mockito: ^5.4.4
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  scroll_to_index: ^3.0.1
  sqflite: ^2.3.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # - assets/lotties/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: MUHAMMADIBold
      fonts:
        - asset: assets/fonts/MUHAMMADIBold.ttf

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#111B21"
  image: assets/images/splash_logo_alquran_light.png
  image_dark: assets/images/splash_logo_alquran_dark.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#111B21"
    image: assets/images/splash_logo_alquran_light.png
    image_dark: assets/images/splash_logo_alquran_dark.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#111B21"
