name: fltr_alquran_if
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_qiblah: ^2.2.0
  flutter_shimmer: ^2.1.2
  geocoding: ^2.1.1
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.1.0
  intl: ^0.18.1
  just_audio: ^0.9.35
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  scroll_to_index: ^3.0.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: MUHAMMADIBold
      fonts:
        - asset: assets/fonts/MUHAMMADIBold.ttf
